name: Blog API CI/CD

on:
    push:
        branches:
            - main
            - feature/*

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install Dependencies
              run: npm ci # Use npm ci for faster and more deterministic installs

            - name: Run Prettier
              run: npm run prettier

            - name: TypeScript Compile Check
              run: npx tsc --noEmit

            - name: Build Project
              run: npm run build

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: blog-api-build
                  path: |
                      dist/
                      .gitignore
                      package.json
                      README.md
                      .env.example
                      .prettierignore
                      .prettierrc
                  include-hidden-files: true
                  retention-days: 1

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Deploy to Render
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                  api-key: ${{ secrets.RENDER_API_KEY }}
                  service-id: ${{ secrets.RENDER_SERVICE_ID }}
